futurehi/urls.py
from django.contrib import admin
from django.urls import path
from sayhi.views import index, new_letter, PublicLetters, donate, LettersView
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', index, name='index'),
                  path('new-letter/', new_letter, name='new_letter'),
                  path('public-letters/', PublicLetters.as_view(), name='public_letters'),
                  path('donate/', donate, name='donate'),
                  path('underworld/<int:pk>/all', login_required(LettersView.as_view()), name='show_letters'),
                  path('underworld/', include('registration.backends.default.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sayhi/models.py
from tkinter import CASCADE

from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Letter(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE)
    text = models.TextField()
    deliver = models.DateField()
    from_mail = models.EmailField()
    is_public = models.BooleanField(default=False)
    is_sent = models.BooleanField(default=False)

    def __str__(self):
        return self.from_mail


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE)
    is_vip = models.BooleanField(default=False)
    picture = models.ImageField(upload_to='profile_images', blank=True)

sayhi/views.py
from django.shortcuts import render, reverse
from django.views.generic import ListView, View, DetailView
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from .form import SendLetter
from django.contrib.auth.decorators import login_required
from .models import Letter
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.utils import timezone
from datetime import date, datetime
import random


# Create your views here.

def index(request):
    send_emails()
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('new_letter'))
    return render(request, 'sayhi/index.html')


@login_required
def new_letter(request):
    form = SendLetter()
    if request.method == 'POST':
        form = SendLetter(request.POST)
        if form.is_valid():
            letter = form.save(commit=False)
            letter.user = request.user
            letter.save()
            return HttpResponseRedirect(reverse('index'))
    return render(request, 'sayhi/new_letter.html', {'form': form})


class PublicLetters(ListView):
    template_name = 'sayhi/public_letters.html'
    context_object_name = 'letters'

    def get_queryset(self):
        return Letter.objects.filter(is_public=True)


def donate(request):
    return render(request, 'sayhi/donate.html')


class LettersView(DetailView):
    model = User
    template_name = 'sayhi/show_letters.html'


def send_emails():
    all_letters = Letter.objects.filter(is_sent=False)
    # Email the profile with the
    # contact information
    template = get_template('sayhi/send_letter.txt')
    for letter in all_letters:
        deliver = datetime.strptime(str(letter.deliver), '%Y-%m-%d')
        if (datetime.today() - deliver).days > 0:
            random_number = random.randint(1, User.objects.count())
            random_user = User.objects.get(pk=random_number)
            context = {
                'from_mail': letter.from_mail,
                'text': letter.text,
            }
            letter_mail = template.render(context)

            email = EmailMessage(
                "یک نامه از گذشته",
                letter_mail,
                "hi@futurehi.ir" + '',
                [random_user.email],
                headers={'Reply-To': letter.from_mail}
            )
            email.send()
            letter.is_sent = True

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    {% block meta %}
    {% endblock %}
    <link rel="shortcut icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon">
    <meta charset="UTF-8">
    <title>فیوچرهای - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/semantic.min.css' %}">
    <script
            src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
</head>

<body>
<div class="ui violet inverted stackable fixed sticky menu rtl">
    <a class="item" href="{% url 'index' %}">
        <img src="{% static 'assets/logo.jpg' %}">
    </a>
    <a class="item" href="{% url 'new_letter' %}">رها کردن نامه‌ای برای آینده</a>
    <a class="item" href="{% url 'public_letters' %}">نامه‌های عمومی</a>
    {% if not user.is_authenticated %}
    <a class="item active" href="{% url 'auth_login' %}"> ورود به جهان زیرین</a>
    {% else %}
    <a class="item active" href="{% url 'auth_logout' %}"> خروج از جهان زیرین</a>
    {% endif %}

</div>

{% block content %}
{% endblock %}

<script src="{% static 'js/semantic.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/sayhi/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    {% block meta %}
    {% endblock %}
    <link rel="shortcut icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon">
    <meta charset="UTF-8">
    <title>فیوچرهای - {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/semantic.min.css' %}">
    <script
            src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
      <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body>
<div class="ui violet inverted stackable fixed sticky menu rtl">
    <a class="item" href="{% url 'index' %}">
        <img src="{% static 'assets/logo.jpg' %}">
    </a>
    <a class="item" href="{% url 'new_letter' %}">رها کردن نامه‌ای برای آینده</a>
    <a class="item" href="{% url 'public_letters' %}">نامه‌های عمومی</a>
    {% if not user.is_authenticated %}
    <a class="item active" href="{% url 'auth_login' %}"> ورود به جهان زیرین</a>
    {% else %}
    <a class="item active" href="{% url 'auth_logout' %}"> خروج از جهان زیرین</a>
    {% endif %}

</div>
{% block sidebar %}
{% endblock %}

{% block content %}
{% endblock %}

<script src="{% static 'js/semantic.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/sayhi/index.html
{% extends 'sayhi/base.html' %}
{% load static %}

{% block title %} هر نامه‌ای یک مقصد داره!{% endblock %}

{% block content %}


<div class="ui stackable three column grid rtl centered">
    <div class="column">
        <img src="{% static 'assets/letter.svg' %}" class="ui fluid rounded image">
    </div>
    <div class="column text-rtl align-centered">
        <p> این‌جا ساحلی از نامه‌های رها شده‌است، نامه‌هایی که بین صفر و یک‌ها حرکت می‌کنن و در زمان درست‌شون می‌رسن به
            آدم‌هایی که حتی انتظارش رو ندارن.
            <br/>
            در فیوچرهای نامه‌ها حرکت می‌کنند، فرستنده‌ها پنهان هستن و گیرنده‌ها به شکل رندوم انتخاب می‌شن. با رها کردن
            اولین نامه، می‌تونی منتظر باشی که روزی یک نامه الهام‌بخش رو از غریبه‌ترین آدم‌های این سرزمین دریافت کنی.
            <br/>
            اغلب نامه‌ها الهام‌بخش یا درد و دل‌ها و کلماتی هستن که معمولا نوشته نمی‌شن. نامه‌های فیوچرهای بخش‌هایی از
            وجود کاملا انسانی و زیبای ما رو نشون می‌ده.
            <br/>
            ما نامه‌رسون‌های آینده‌ایم. بین آدم‌ها.</p>
    </div>
</div>

{% endblock %}

templates/sayhi/new_letter.html
{% extends 'sayhi/sidebar.html' %}
{% load static %}
{% load semanticui %}

{% block title %} نوشتن نامه جدید{% endblock %}

{% block content %}
<div class="eight wide column align-centered">
    <form class="ui form text-rtl big" method="post" action=".">
        {% csrf_token %}
        <div class="ui field">
            {{ form.text.errors }}
            {% render_field form.text placeholder="سلام غریبه، حالت خوبه؟" %}
        </div>
        <div class="ui fields">
            <div class="ui calendar" id="calender">
                {{ form.deliver.errors }}
                {% render_field form.deliver %}
                {{ form.media }}
            </div>
        </div>
        <div class="ui field">
            {{ form.from_mail.errors }}
            {% render_field form.from_mail %}
        </div>
        <div class="ui field">
            {{ form.is_public.errors }}
            <div class="ui toggle checkbox">
                {% render_field form.is_public %}
            </div>
        </div>
        <button class="ui button violet rtl" type="submit">رها کردن نامه</button>
    </form>
</div>
</div>
{% endblock %}

templates/sayhi/public_letters.html
{% extends 'sayhi/base.html' %}
{% load static %}
{% load semanticui %}
{% load jalali_tags %}

{% block title %} همه نامه‌های عمومی{% endblock %}

{% block content %}
<div class="ui grid stackable container rtl text-rtl">
    {% for letter in letters %}
    <div class="six wide column">
        <div class="ui piled segment rtl text-rtl">
            <h4 class="ui header rtl text-rtl">ارسال شده به {{ letter.deliver|to_jalali:'%y/%m/%d' }}</h4>
            {{ letter.text }}
        </div>
    </div>
    {% endfor %}
    <div class="column ui four wide">
        <img src="{% static 'assets/public.svg' %}" class="ui fluid rounded image">
    </div>
</div>
{% endblock %}

templates/sayhi/show_letters.html
{% extends 'sayhi/sidebar.html' %}
{% load static %}
{% load semanticui %}
{% load jalali_tags %}

{% block title %} همه‌ی نامه‌های من{% endblock %}
{% block content %}

    <div class="ui eight wide column">
        <div class="ui grid stackable container">
            {% for letter in user.letter_set.all %}
            <div class="six wide column">
                <div class="ui piled segment rtl text-rtl">
                    <h4 class="ui header rtl text-rtl">ارسال شده به {{ letter.deliver|to_jalali:'%y/%m/%d' }}</h4>
                    {{ letter.text }}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>

{% endblock %}

templates/sayhi/sidebar.html
{% extends 'sayhi/base.html' %}
{% load static %}
{% load semanticui %}

{% block sidebar %}

<div class="ui stackable two column grid rtl text-rtl centered" style="padding-top: 1%;">
    <div class="ui four wide column">
        <div class="violet inverted massive right ui vertical menu rtl text-rtl">
            {% if user.is_authenticated %}
            <a class="active item" href="{% url 'show_letters' user.id %}">
                <div class="teal ui small teal label rtl" style="float:left;">{{ user.letter_set.count }}</div>
                نامه‌های رها شده من
            </a>
            {% endif %}
            <div class="item">
                <h4 class="ui header rtl">جهان زیرین</h4>
                <span>جهان زیرین، جهان گذشته‌هاست، نامه‌رسان‌های ما همیشه درحال پرسه زدن بین اون‌هان، همراه با <a
                        href="https://fa.wikipedia.org/wiki/%D9%87%D8%A7%D8%AF%D8%B3">هادس</a> تا زمان درست فرا برسه، آینده تبدیل به حال بشه، اون‌وقت نامه‌رسان‌های ما به دنیای زنده‌ها بر می‌گردن و نامه‌ها می‌رسن به آدم‌ها. با تمام حس و حال درون‌شون.</span>
            </div>
            <div class="item">
                <h4 class="ui header rtl">در جهان زیرین چه خبره؟</h4>
                <p>به محض ثبت‌نام در سایت، می‌تونید به جهان زیرین وارد بشید، اون‌جا نامه‌های بهتری می‌تونید بنویسید.
                    نامه‌هایی به مقصد خاص، یا حتی خودتون در آینده. تاریخچه همه نامه‌های قبلی‌تون هم توسط نامه‌رسان‌ها
                    ثبت
                    شده.</p>
            </div>
            {% if user.is_authenticated %}
            <div class="item">
                <h4 class="ui header rtl">انجمن صنفی نامه‌رسان‌های آینده</h4>
                <p>شما می‌تونید به انجمن صنفی این نامه‌رسان‌ها بپیوندید. یک جای باحال برای اطمینان از تحویل نامه‌های
                    آینده! <br/> <br/>
                    <a class="button" href="{% url 'donate' %}">
                        <button class="ui button inverted rtl" type="button">برو به انجمن نامه‌رسان‌های آینده</button>
                    </a>
                </p>
            </div>
            {% endif %}
        </div>
    </div>
    {% endblock %}

    {% block content %}
    {% endblock %}